---
title: "hw04-Renyi-Wang"
author: "Ren Yi Wang"
date: "April 13, 2018"
output: github_document
---

```{r}
library(stringr)
library(XML)
library(ggplot2)
source('../code/archive-functions.R')
knitr::opts_chunk$set(echo=TRUE, error=TRUE, fig.path='../images/')
```

## 1.1) Read Archive Data Table

```{r}
raw_data <- read_archive('stringr')
raw_data
```

## 1.2) Data Cleaning

```{r}
clean_data <- clean_archive(raw_data)
clean_data
```

## 1.3) Timeline plot

```{r}
plot_archive(clean_data)
```

## 1.4) Archive of "stringr"

```{r}
raw_data <- read_archive('stringr')
clean_data <- clean_archive(raw_data)
plot_archive(clean_data)
```

## 1.5) Archives of "splyr", "ggplot2", "XML", and "knitr"

```{r}
raw_dplyr <- read_archive("dplyr")
raw_ggplot <- read_archive("ggplot2")
raw_xml <- read_archive("XML")
raw_knitr <- read_archive("knitr")

clean_dplyr <- clean_archive(raw_dplyr)
clean_ggplot <- clean_archive(raw_ggplot)
clean_xml <- clean_archive(raw_xml)
clean_knitr <- clean_archive(raw_knitr)

write.csv(clean_dplyr, '../data/dplyr-archive.csv', row.names = TRUE)
write.csv(clean_ggplot, '../data/ggplot2-archive.csv', row.names = TRUE)
write.csv(clean_xml, '../data/XML-archive.csv', row.names = TRUE)
write.csv(clean_knitr, '../data/knitr-archive.csv', row.names = TRUE)

merged_data <- rbind(clean_dplyr,clean_ggplot,clean_xml,clean_knitr)

years <- vector(mode = "numeric")
             
for (i in 1:length(merged_data$date)) {
    time <- as.numeric(str_split(merged_data$date,pattern = "-")[[i]])
    years[i] <- time[1] + time[2]/12 + time[3]/365 
}  

ggplot(merged_data, aes(x = years, y = as.numeric(merged_data$size))) +
  geom_step(aes(group = name, color = name)) +
  xlab('date') +
  ylab('Size(Kilobytes)')

ggplot(merged_data, aes(x = years, y = as.numeric(merged_data$size))) +
  geom_step(aes(color = name)) + 
  facet_wrap(~name, scales = 'free') +
  xlab('date') +
  ylab('Size(Kilobytes)')
```

## 2.1) Splitting Characters

```{r}
source('../code/regex-functions.R')

split_chars('Go Bears!')
split_chars('Expecto Patronum')
```

## 2.2) Number of Vowels

```{r}
vec <- c('G', 'o', ' ', 'B', 'e', 'a', 'r', 's', '!')
num_vowels(vec)
```

## 2.3) Counting Vowels

```{r}
count_vowels("The quick brown fox jumps over the lazy dog")
count_vowels("THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG")
```

## 2.4) Reversing Characters

```{r}
reverse_chars("gattaca")
reverse_chars("Lumox Maxima")
```

## 2.5) Reversing Sentences by Words

```{r}
reverse_words("sentence! this reverse")
reverse_words("string")
```

## 3.1) Number of characters per tweet

```{r}
text <- read.csv('../data/text-emotion.csv')

content_vec <- as.vector(text$content)
char_num <- vector(mode = 'numeric')

for (i in 1:length(text$content)) {
  char_num[i] <- length(split_chars(content_vec[i]))
}

summary(char_num)

hist(char_num)
```

## 3.2) Number of Mentions

```{r}
num_at <- str_count(text$content, pattern = '@[a-zA-Z0-9_]{1,15}')
at_table <- table(num_at)
barplot(at_table)

vec_10_more <- num_at == 10
text$content[vec_10_more]
```

## 3.3) Hashtags

```{r}
num_hash <- str_count(text$content, pattern = '#[[:alpha:]][[:alnum:]]*')
sum(num_hash)
hash_table <- table(num_hash)
barplot(hash_table)


hash_vec <- na.omit(str_extract(text$content, pattern = '#[[:alpha:]][[:alnum:]]*'))
hash_length <- nchar(hash_vec) - 1
len_avg <- mean(hash_length)
len_avg

hashtag_table <- table(hash_length)
mode <- names(hashtag_table[hashtag_table == max(hashtag_table)])
mode
```







